version: 2

aliases:
- &GCP-auth
  name: GCP Authenticate
  command: |
    echo 'export GCLOUD_SERVICE_KEY="$GCLOUD_SERVICE_KEY"' >> $BASH_ENV
    /tools/gcp_authenticate.sh
- &docker-login
  name: Docker login
  command: |
    docker login -u _json_key --password-stdin https://eu.gcr.io <<< "${DOCKER_PASSWORD}"
- &tag-git-version
  name: Tag git commit with build version and push to github
  command: |
    git config --global user.email "circleci@entur.no"
    git config --global user.name "circleci"
    git tag $VERSION
    git push origin $VERSION
- &create-image-version
  name: Create new image version and store to env
  command: |
    echo "export VERSION=$CIRCLE_BRANCH-v$CIRCLE_BUILD_NUM-$(echo -n $CIRCLE_SHA1 | tail -c 8)"  >> $BASH_ENV
- &docker-build-and-push
  name: Docker build and push
  command: |
    IMAGE="eu.gcr.io/entur-system-1287/${CIRCLE_PROJECT_REPONAME}"
    echo "Image: ${IMAGE}"
    docker build -t $IMAGE .
    docker tag $IMAGE "${IMAGE}":"${VERSION}"
    docker push $IMAGE

jobs:
  deploy-docker:
    docker:
    - image: eu.gcr.io/entur-system-1287/circleci-toolbox-image-java11
      auth:
        username: _json_key
        password: $DOCKER_PASSWORD
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run: *GCP-auth
    - run: *create-image-version
    - run: *tag-git-version
    - run: *docker-login
    - run: *docker-build-and-push

workflows:
  version: 2
  deploy:
    jobs:
    - deploy-docker:
        context: global
        filters:
          branches:
            only: master