# For help and tutorials, visit https://circleci.com/docs/
# For internal documentation visit https://enturas.atlassian.net/wiki/spaces/ESP/pages/580026490/CircleCI
version: 2.1

orbs:
#  slack: circleci/slack@1.0.0
  docker: circleci/docker@0.5.20

workflows:
  "Build Pipeline":
    jobs:
      - docker/publish:
          name: publish
          registry: $DOCKER_REGISTRY
          image: $CIRCLE_PROJECT_REPONAME
          tag: '${CIRCLE_BRANCH#"env/"}-v$CIRCLE_BUILD_NUM,latest'
          deploy: true
          context: global
