
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.name" . }}-nibiru-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | indent 4 }}
data:
  application.properties: |-
      application.url=http://0.0.0.0:4000/nibiru/api
      spring.main.sources=org.rutebanken.nibiru
      destination.url=http://localhost:3000/v1
      logging.level.org.rutebanken.nibiru=INFO
      processor.map.counties.enabled=true