apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    {{- include "common.labels" . | indent 4 }}
  name: {{ template "app.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: geocoder-acceptance-tests
            image: {{ .Values.image.identifier }}
            imagePullPolicy: {{ .Values.image.imagePullPolicy }}
            args: ["{{ .Values.environment.testArg }}"]
            env:
            - name: SLACK_URL
              valueFrom:
                secretKeyRef:
                  key: slack-url
                  name: {{ .Values.environment.slackUrl }}
            resources:
              limits:
                cpu: {{ .Values.resources.cpuLimit }}
                memory: {{ .Values.resources.memLimit }}
              requests:
                cpu: {{ .Values.resources.cpuRequest }}
                memory: {{ .Values.resources.memRequest }}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 0 0 0 0 0
  successfulJobsHistoryLimit: 1
  suspend: true
status: {}
