apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    {{- include "common.labels" . | indent 4 }}
  name: {{ template "app.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      # delete completed or failed jobs after 3 days (to give some time for error analysis)
      # jobs should normally be deleted automatically by marduk after graph building completion
      ttlSecondsAfterFinished: 259200
      template:
        spec:
          containers:
          - name: geocoder-acceptance-tests
            image: {{ .Values.image.identifier }}
            imagePullPolicy: {{ .Values.image.imagePullPolicy }}
            args: ["{{ .Values.environment.testArg }}"]
            env:
            - name: GOOGLE_PROJECT_ID
              value: {{ .Values.environment.projectId }}
            - name: SLACK_URL
              valueFrom:
                secretKeyRef:
                  key: slack-url
                  name: {{ .Values.environment.slackUrl }}
            resources:
              limits:
                cpu: {{ .Values.resources.cpuLimit }}
                memory: {{ .Values.resources.memLimit }}
              requests:
                cpu: {{ .Values.resources.cpuRequest }}
                memory: {{ .Values.resources.memRequest }}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              capabilities:
                drop: ["ALL"]
              seccompProfile:
                type: RuntimeDefault
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 30
          securityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            fsGroup: 1000

  schedule: 0 0 * * *
  successfulJobsHistoryLimit: 1
  suspend: true
status: {}
