apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    {{- include "common.labels" . | indent 4 }}
  name: {{ template "app.name" . }}-predeploy
  namespace: {{ .Release.Namespace }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      # delete completed or failed jobs after 3 days (to give some time for error analysis)
      # jobs should normally be deleted automatically by marduk after graph building completion
      ttlSecondsAfterFinished: 259200
      activeDeadlineSeconds: 300
      template:
        spec:
          containers:
          - name: elasticsearch
            image: eu.gcr.io/entur-system-1287/es-static
            imagePullPolicy: Always
            env:
            - name: GCS_BASE_PATH
              value: {{ .Values.environment.gcsBasePath }}
            resources:
              limits:
                cpu: 2
                memory: 1600Mi
              requests:
                cpu: 500m
                memory: 1600Mi
            ports:
            - containerPort: 9200
              protocol: TCP
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          - name: pelias-api
            image: eu.gcr.io/entur-system-1287/pelias
            imagePullPolicy: Always
            ports:
            - containerPort: 3000
              protocol: TCP
            resources:
              limits:
                cpu: 800m
                memory: 750Mi
              requests:
                cpu: 200m
                memory: 500Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          - name: nibiru
            image: eu.gcr.io/entur-system-1287/nibiru
            imagePullPolicy: Always
            env:
              - name: JAVA_OPTIONS
                value: -server -Xmx500m -Dspring.config.location=/etc/application-config/application.properties
                      -Dfile.encoding=UTF-8
              - name: TZ
                value: Europe/Oslo
            resources:
              limits:
                cpu: 1
                memory: 750Mi
              requests:
                cpu: 200m
                memory: 650Mi
            volumeMounts:
              - mountPath: /etc/application-config
                name: nibiru-application-config
                readOnly: true
            ports:
              - containerPort: 4000
                name: http
                protocol: TCP
          - name: geocoder-acceptance-tests
            image: {{ .Values.image.identifier }}
            imagePullPolicy: {{ .Values.image.imagePullPolicy }}
            args: ["local"]
            env:
            - name: LOCAL
              value: "true"
            - name: PUBSUB_TOPIC
              value: {{ .Values.environment.pubsubTopic }}
            - name: GOOGLE_PROJECT_ID
              value: {{ .Values.environment.projectId }}
            - name: SLACK_URL
              valueFrom:
                secretKeyRef:
                  key: slack-url
                  name: {{ .Values.environment.slackUrl }}
            resources:
              limits:
                cpu: {{ .Values.resources.cpuLimit }}
                memory: {{ .Values.resources.memLimit }}
              requests:
                cpu: {{ .Values.resources.cpuRequest }}
                memory: {{ .Values.resources.memRequest }}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: application
          serviceAccountName: application
          terminationGracePeriodSeconds: 30
          volumes:
            - name: nibiru-application-config
              configMap:
                name: {{ template "app.name" . }}-nibiru-config
                defaultMode: 420
  schedule: 0 0 * * *
  successfulJobsHistoryLimit: 1
  suspend: true
status: {}
