env: dev

environment:
  testArg: dev
  slackUrl: ror-dev-slack-url
  projectId: ent-kub-dev
  pubsubTopic: projects/ent-kakka-dev/topics/GecoderAcceptanceTestsPreDeployResult
  gcsBasePath: gs://kakka-dev/es-data/
